# Generated by Django 5.2.4 on 2025-08-02 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection_id', models.CharField(max_length=10, unique=True)),
                ('connection_type', models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial')], max_length=20)),
                ('start_date', models.DateField()),
                ('occupation', models.CharField(max_length=100)),
                ('load', models.DecimalField(decimal_places=2, max_digits=10)),
                ('plot_no', models.CharField(max_length=50)),
                ('pincode', models.CharField(max_length=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumer_id', models.CharField(max_length=20)),
                ('month', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
                ('current_reading', models.DecimalField(decimal_places=2, max_digits=10)),
                ('previous_reading', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_units', models.DecimalField(decimal_places=2, max_digits=10)),
                ('charge_per_unit', models.DecimalField(decimal_places=2, max_digits=5)),
                ('due_date', models.DateField()),
                ('is_paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ebsapp.connection')),
            ],
        ),
        migrations.AddField(
            model_name='connection',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ebsapp.customer'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('card_number', models.CharField(max_length=16)),
                ('expiry_date', models.CharField(max_length=10)),
                ('cvc', models.CharField(max_length=4)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ebsapp.bill')),
            ],
        ),
    ]
